# -*- coding: utf-8 -*-
"""
Created on Wed Sep 18 13:50:23 2019
@author: Ju-Hyun Lee, Hee Cho, Ki-Hyung Hong

"""

element ={ 'speak' :{'attr' : ['lang' , 'base', 'onlangfailure' , 'startmark', 'endmark' , 'version','schemaLocation'] , 
                     'requiredAttr' : ['lang' , 'version'],
                      'child' : ['audio', 'break', 'emphasis', 'lang', 'lexicon','lookup', 'mark','meta','metadata' , 'phoneme', 'prosody', 'say-as', 
                    'sub', 'token', 'voice','w','p','s', 'emotion','g2p']},
            'p' : {'attr' : ['lang' , 'id' , 'onlangfailure'] , 
                   'requiredAttr' : [],
                      'child' : ['audio', 'break', 'emphasis', 'lang', 'lookup', 
                                 'mark', 'phoneme', 'prosody', 'say-as', 'sub', 
                                 'token', 'voice','w','p','s' ,'emotion','g2p' ]},
               's' : {'attr' : ['lang' , 'id' , 'onlangfailure'] ,
                      'requiredAttr' : [],
                      'child' : ['audio', 'break', 'emphasis', 'lang', 'lookup', 
                                'mark', 'phoneme', 'prosody', 'say-as', 
                                'sub', 'token', 'voice','w','emotion','g2p' ]},
               'w' : {'attr' : ['lang' , 'id' , 'onlangfailure' , 'role'] , 
                      'requiredAttr' : [],
                      'child' : ['audio', 'break', 'emphasis', 'mark', 
                                'phoneme', 'prosody', 'say-as', 'sub', 'emotion']},
               'token' : {'attr' : ['lang' , 'id' , 'onlangfailure' , 'role'] , 
                          'requiredAttr' : [],
                          'child' : ['audio', 'break', 'emphasis', 
                                     'mark', 'phoneme', 'prosody', 'say-as', 
                                     'sub', 'emotion']},
               'say-as' : {'attr' : ['interpret-as' , 'format' , 'detail' ] , 
                           'requiredAttr' : ['interpret-as'],
                           'child' : []},
               'phoneme' : {'attr' : ['ph' , 'alphabet' , 'type' ] , 
                            'requiredAttr' : ['ph'],
                            'child' : []},
               'sub' : {'attr' : ['alias' ] , 
                        'requiredAttr' : ['alias'],
                        'child' : []},
               'lang' : {'attr' : ['lang' , 'onlangfailure' ] ,
                         'requiredAttr' : ['lang'],
                         'child' : ['audio', 'break', 'emphasis', 'lang', 'lookup', 
                                    'mark', 'phoneme', 'prosody', 'say-as',
                                    'sub', 'token', 'voice','w','p','s' ,'emotion']},
               'voice' : {'attr' : ['gender' , 'age', 'variant' , 'name', 'languages', 
                                    'required' , 'ordering' , 'onvoicefailure' ] , 
                        'requiredAttr' : [],
                          'child' : ['audio', 'break', 'emphasis', 'lang', 'lookup', 
                                     'mark', 'phoneme', 'prosody', 'say-as', 
                                     'sub', 'token', 'voice','w','p','s' ,'emotion']},
               'emphasis' : {'attr' : ['level'] , 
                             'requiredAttr' : [],
                             'child' : ['audio', 'break', 'emphasis', 'lang', 
                                        'lookup', 'mark', 'phoneme', 'prosody', 'say-as', 
                                        'sub', 'token', 'voice','w','emotion']},
               'break' : {'attr' : ['time' , 'strength' ] , 
                          'requiredAttr' : [],
                          'child' : []},
               'prosody' : {'attr' : ['pitch' , 'contour' , 'range', 'rate' , 'duration' , 'volume' ] ,
                            'requiredAttr' : [],
                            'child' : ['audio', 'break', 'emphasis', 'lang', 'lookup',
                                       'mark', 'phoneme', 'prosody', 'say-as', 
                                       'sub', 'token', 'voice','w','p','s' ,'emotion']},
               'audio' : {'attr' : ['src' , 'fetchtimeout' , 'fetchhint' ,'maxage', 'maxstale' , 'clipBegin', 
                                    'clipEnd', 'repeatCount' , 'repeatDur' , 'soundLevel', 'speed'] , 
                          'requiredAttr' : [],
                          'child' : ['audio', 'break', 'emphasis', 'lang', 'lookup', 
                                     'mark', 'phoneme', 'prosody', 'say-as', 
                                     'sub', 'token', 'voice','w','p','s' ,'desc','emotion']},
               'mark' : {'attr' : ['name'] , 
                         'requiredAttr' : ['name'],
                         'child' : []},
               'desc' : {'attr' : ['lang' , 'onlangfailure'] ,
                         'requiredAttr' : [],
                         'child' : []},
               'lexicon' : {'attr' : ['URI', 'id' , 'type' , 'fetchtimeout' , 'maxage', 'maxstale'] , 
                            'requiredAttr' : ['URI' , 'id'],
                            'child' : []},
               'lookup' : {'attr' : ['ref'] , 
                           'requiredAttr' : ['ref'],
                           'child' : ['audio', 'break', 'emphasis', 'lang', 'lookup', 
                                      'mark', 'p','phoneme', 'prosody', 'say-as', 
                                      'sub', 'token', 'voice','w' ]},
               'meta' : {'attr' : ['name', 'http-equiv' , 'content'] ,
                         'requiredAttr' : ['name'],
                         'child' : []},
               'emotionml' : {'attr': ['version' , 'category-set' , 'dimension-set' , 'appraisal-set' , 
                                            'action-tendency-set'],
                             'requiredAttr' : ['version'],
                                    'child' : ['emotion' , 'info' , 'vocabulary']},
                'emotion' : {'attr': ['version' , 'id' , 'category-set' , 'dimension-set' , 'appraisal-set' , 
                                            'action-tendency-set', 'start' , 'end' , 'duration' , 'time-ref-uri' ,
                                            'time-ref-anchor-point' , 'offset-to-start' , 'expressed-through' ],
                             'requiredAttr' : [],
                            'child' : ['category' , 'dimension' , 'appraisal' , 'action-tendency' , 'reference']},
                'category' : {'attr': ['name' , 'value' , 'confidence'],
                              'requiredAttr' : ['name'],
                                  'child' : ['trace']},
                'dimension' : {'attr': ['name' , 'value' , 'confidence'],
                               'requiredAttr' : ['name'],
                                   'child' : ['trace']},
                'appraisal' : {'attr': ['name' , 'value' , 'confidence'],
                               'requiredAttr' : ['name'],
                                   'child' : ['trace']},
                'action-tendency' : {'attr': ['name' , 'value' , 'confidence'],
                                     'requiredAttr' : ['name'],
                                         'child' : ['trace']},
                'info' : {'attr': ['id'],
                          'requiredAttr' : [],
                          'child' : []},
                'reference' : {'attr': ['uri' , 'role' , 'media-type'],
                               'requiredAttr' : ['uri'],
                               'child' : []},
                    'trace' : {'attr': ['freq' , 'samples'],
                               'requiredAttr' : ['freq' , 'samples'],
                               'child' : []},
                    'vocabulary' : {'attr': ['type' , 'id' ],
                                    'requiredAttr' : ['type' , 'id'],
                                    'child' : ['item']},
                    'item' : {'attr': ['name' ],
                              'requiredAttr' : ['name'],
                              'child' : ['info']},
              'g2p' : {'attr' : ['mode' , 'source_lang' , 'target_lang'],
                       'requiredAttr' : [],
                       'child' : []}

          }
               
emotionmlElement = {'emotionml' : {'attr': ['version' , 'category-set' , 'dimension-set' , 'appraisal-set' , 
                                            'action-tendency-set'],
                                    'child' : ['emotion' , 'info' , 'vocabulary']},
                    'emotion' : {'attr': ['version' , 'id' , 'category-set' , 'dimension-set' , 'appraisal-set' , 
                                            'action-tendency-set', 'start' , 'end' , 'duration' , 'time-ref-uri' ,
                                            'time-ref-anchor-point' , 'offset-to-start' , 'expressed-through' ],
                                 'child' : ['category' , 'dimension' , 'appraisal' , 'action-tendency' , 'reference']},
                    'category' : {'attr': ['name' , 'value' , 'confidence'],
                                  'child' : ['trace']},
                    'dimension' : {'attr': ['name' , 'value' , 'confidence'],
                                   'child' : ['trace']},
                    'appraisal' : {'attr': ['name' , 'value' , 'confidence'],
                                   'child' : ['trace']},
                    'action-tendency' : {'attr': ['name' , 'value' , 'confidence'],
                                         'child' : ['trace']},
                    'info' : {'attr': ['id'],
                              'child' : []},
                    'reference' : {'attr': ['uri' , 'role' , 'media-type'],
                                   'child' : []},
                    'trace' : {'attr': ['freq' , 'samples'],
                               'child' : []},
                    'vocabulary' : {'attr': ['type' , 'id' ],
                                    'child' : ['item']},
                    'item' : {'attr': ['name' ],
                              'child' : ['info']}
                    }

g2pElement = {'g2p' : {'attr' : ['mode' , 'source_lang' , 'target_lang'],
                       'child' : []}}


